version: "3"
services:
  api:
    container_name: projectApi
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    expose:
      - 3000
    ports:
      - 3000:3000
    # depends_on:
    #   - pg
    # command: bash -c 'yarn migration:run && yarn dev'
    command: bash -c 'yarn dev'
  # pg:
  #   container_name: projectApiPg
  #   image: postgres
  #   env_file:
  #     - .env
  #   expose:
  #     - 5432
  #   ports:
  #     - 5432:5432
